# Generated by Django 5.1.1 on 2024-09-05 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Plat',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='plat', serialize=False, to='cantine.menu')),
                ('name', models.CharField(max_length=255)),
                ('summary', models.TextField()),
            ],
        ),
    ]
